name: rules-sync
on:
  issues:
    types: [opened, edited]

jobs:
  sync:
    if: contains(github.event.issue.title, '設定を変更する')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Parse issue → rules.yml
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: python tools/issue2rules.py

      - name: Commit rules.yml
        run: |
          git config user.name "rules-sync-bot"
          git config user.email "actions@users.noreply.github.com"
          git add rules.yml
          git commit -m "Update rules.yml from issue #${{ github.event.issue.number }}" || echo "no changes"
          git push
